# Generated by Django 3.2.16 on 2025-11-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
