# Generated by Django 3.2.16 on 2025-11-22 10:32
from django.db import migrations


def populate_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('blog', 'Profile')

    for user in User.objects.all():
        Profile.objects.get_or_create(
            user=user,
            defaults={
                "get_full_name": f"{user.first_name} {user.last_name}",
                "is_staff": user.is_staff,
                "username": user.username,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profile_username'),
    ]

    operations = [
        migrations.RunPython(populate_profiles),
    ]