# Generated by Django 3.2.16 on 2025-10-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
