# Generated by Django 3.2.16 on 2025-11-19 16:10

from django.db import migrations, models
from django.contrib.auth.models import User
from blog.models import Profile  # замените yourapp на название вашего приложения


def forwards(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('blog', 'Profile')  # замените yourapp на название вашего приложения

    for user in User.objects.all():
        if not Profile.objects.filter(user=user).exists():
            Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
